 <style>
     @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
     /* Styles généraux */

     body {
         font-family: 'Press Start 2P', sans-serif;
         /* Utilisation de la hauteur à 100% pour occuper tout l'écran */
     }
 </style>
 <h3>LES JEUX EN VEDETTE</h3>

 <div class="articles">
     <img src="public/jeux/bo1.jpg" alt="Article 1">
     <h2>CALL OF DUTY : BLACK OPS</h2>
     <p>Call of Duty: Black Ops 1 est un jeu de tir à la première personne qui vous transporte au cœur des opérations clandestines les plus dangereuses de la Guerre froide. Développé par Treyarch et édité par Activision, ce jeu captivant offre une expérience de jeu immersive, mêlant une histoire palpitante, un gameplay intense et des graphismes saisissants...</p>
     <a href="#">Lire l'article</a>
 </div>
 <div class="articles">
     <img src="public/jeux/god_of_war_ghost_of_sparta.jpg" alt="Article 2">
     <h2>GOD OF WAR : GHOST OF SPARTA</h2>
     <p>Plongez dans l'univers épique de God of War: Ghost of Sparta, où Kratos, le légendaire guerrier spartiate, se lance dans une quête émouvante à la recherche de la vérité sur son passé. Affrontez des dieux, des monstres titanesques et des créatures mythiques dans des combats épiques...</p>
     <a href="#">Lire l'article</a>
 </div>
 <div class="articles">
     <img src="public/jeux/PACKSHOT_GAME-T8-Deluxe_Edition__36079.jpg" alt="Article 2">
     <h2>TEKKEN 8</h2>
     <p>Entrez dans l'arène de Tekken 8, le dernier opus de la célèbre franchise de jeux de combat. Affrontez une multitude de combattants aux styles de combat uniques dans des affrontements intenses et stratégiques. Avec des graphismes à couper le souffle, des mouvements fluides et une jouabilité exaltante, Tekken 8 promet d'offrir une expérience de combat ultime pour les fans de la série et les nouveaux venus...</p>
     <a href="#">Lire l'article</a>
 </div>
 <!-- Ajoutez plus d'articles ici si nécessaire -->
 </div>