<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/css/face.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Game Blog</title>
</head>

<body>
    <!-- HEADER COMMUN-->
    <header class=" text-white">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="home"><span class="text-danger">Ze</span>GAMEBLOG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="home"><span class="text-danger">AC</span>CUEIL</a></li>
                        <li class="nav-item"><a class="nav-link" href="add_article"><span class="text-danger">AJ</span>OUTE UN ARTICLE</a></li>
                        <li class="nav-item"><a class="nav-link" href="article"><span class="text-danger">AR</span>TICLES</a></li>
                        <?php
                        if (isset($_SESSION['username'])) {
                            echo '<li class="nav-item"><a class="nav-link" href="profile">Vous êtes connecté</a></li>';
                        } else {
                            echo '<li class="nav-item"><a class="nav-link" href="login"><span class="text-danger">CO</span>NNECTE TOI </a></li>';
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </nav>

        <section class="hero text-center py-5">
            <div class="container">
                <h2><span class="text-danger">Dé</span>couvrez le monde des jeux vidéo</h2>
                <p>Bienvenue sur notre blog dédié aux jeux vidéo. Explorez nos articles, et plongez dans l'univers passionnant des jeux vidéo.</p>
                <a href="article" class="btn">Découvrir nos articles</a>

            </div>
        </section>

    </header>

    <!-- MAIN -->
    <main class="py-4">
        <div class="container">
            <!-- AFFICHAGE DU TEMPLATE CORRESPONDANT À LA VIEW VISÉ -->
            <?php include $this->template . '.phtml' ?>
        </div>
    </main>

    <!-- FOOTER COMMUN-->
    <footer class="text-white py-3">
        <div class="container text-center">
            <p>&copy; 2024 Blog de Jeux Vidéo. Tous droits réservés.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-pyIbS5tEkWVFX6k4u8bEu5Wc/W6ifz+djq33U5IjV27CI2hlHDIToKxfLDaJRDA" crossorigin="anonymous"></script>
</body>

</html>