<style>
    @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
    /* Styles généraux */

    body {
        font-family: 'Press Start 2P', sans-serif;
        /* Utilisation de la hauteur à 100% pour occuper tout l'écran */
    }

    li {
        color: yellowgreen;
    }

    h1 {
        color: red;
    }

    h2 {
        color: white;
    }
</style>
<?php if (isset($_SESSION['username'])) : ?>

    <h1>Bienvenue sur votre profil
        <?= $_SESSION['username'] ?>
    </h1>

    <section>
        <h2>Vos informations</h2>
        <ul>

            <li>Prénom:
                <?= $_SESSION['username'] ?>
            </li>
            <li>Email:
                <?= $_SESSION['email'] ?>
            </li>
        </ul>

        <a href="index.php?url=updateProfile&id=<?php echo $_SESSION['user_id']; ?>">Modifier mon profil</a>
        <div>
            <p>N'oubliez pas de vous <a href="?url=logout">Déconnecter</a></p>
        </div>
        <a href="index.php?url=confirm">Supprimer le profil définitivement</a>
    </section>
<?php else : ?>
    <?= header('Location: index.php?url=login') ?>
<?php endif ?>