<style>
	.form-register {
		color: red;
	}

	@import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
	/* Styles généraux */

	body {
		font-family: 'Press Start 2P', sans-serif;
		/* Utilisation de la hauteur à 100% pour occuper tout l'écran */
	}
</style>
<h1>Créer un nouveau compte:</h1>

<section id="register" class="col s12">
	<form class="col s12" method="POST" action="index.php?url=register">
		<article class="form-register">

			<div class="input-field col s6">
				<label for="username">Prénom</label>
				<input id="username" name="username" type="text" class="validate">
			</div>

			<div class="input-field col s12">
				<label for="email">Email</label>
				<input id="email" type="email" name="email" class="validate">
			</div>

			<div class="input-field col s12">
				<label for="password">Mot de passe</label>
				<input id="password" name="password" type="password" class="validate">
			</div>

			<div class="register">
				<button class="btn-register" type="submit" name="submit">Soumettre</button>
			</div>
		</article>
	</form>
</section>
</div>