<?php if (isset($_SESSION['firstname'])): ?>

<h1>Modifier mes informations</h1>
<form id="updateForm" action="index.php?url=updateProfile&id=<?php echo $_SESSION['user_id']; ?>" method="POST">
    <label for="firstname">Prénom :</label>
    <input type="text" id="firstname" name="firstname" value="<?= $_SESSION['firstname'] ?>"><br>

    <label for="lastname">Nom :</label>
    <input type="text" id="lastname" name="lastname" value="<?= $_SESSION['lastname'] ?>"><br>

    <label for="email">Email :</label>
    <input type="email" id="email" name="email" value="<?= $_SESSION['email'] ?>"><br>

    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" value="<?= $_SESSION['password'] ?>"><br>

    <input type="submit" value="Mettre à jour">

</form>

<!-- <a href="index.php?url=confirm">Supprimer le profil définitivement</a> -->
<?php else: ?>
<?= header('Location: index.php?url=login') ?>
<?php endif ?>

<script>

    const form = document.querySelector("#updateForm");

    // Fonction pour mettre à jour les informations du profil en temps réel
    function updateProfile(e) {

        // Récupérer les données du formulaire
        const formData = new FormData(form);

        // Effectuer une requête fetch vers le serveur pour récupérer les nouvelles données du profil
        fetch(form.action, {
            method: "POST",
            body: formData,
        })
            .then((response) => {
                console.log(response);
                if (!response.ok) {
                    throw new Error("Erreur lors de la récupération des données du profil");
                }
                return response.json();
                // console.log(response);
            })
            .then((userData) => {
                console.log(userData);
                // Mettez à jour les informations affichées sur la page avec les nouvelles données
                form.querySelector("#firstname").value = userData.firstname;
                form.querySelector("#lastname").value = userData.lastname;
                form.querySelector("#email").value = userData.email;
                form.querySelector("#password").value = userData.password;
            })
            .catch((error) => {
                // Affichez un message d'erreur ou effectuez une action appropriée en cas d'erreur
                console.error(error.message);
            });
    }

    // Récupérer le formulaire de mise à jour du profil
    //const updateForm = document.querySelector("#updateForm");

    // Ajouter un écouteur d'événements sur l'événement "submit" du formulaire
    form.addEventListener("submit", updateProfile);

</script>